apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pet-clinic
resources:
  - namespace.yaml
  - db.yaml
  - petclinic.yaml
  - ingress.yaml

# Toggle remote JDWP debugging (dev demos only — never leave on in prod).
# Comment out the first patch entry below to disable (prod).

patches:
  - path: components/remote-debug/patch.yaml
    target:
      kind: Deployment
      name: petclinic

# Update the routing rule to match your FQDN
  - target:
      kind: Ingress
      name: spring-cloud-petclinic-service
    patch: |
      # 1. Update the routing rule to match your raw IP address
      - op: replace
        path: /spec/rules/0/host
        value: "petclinic.local" # <-- Replace this with your FQDN

# Update Image Location of petclinic
images:
  - name: dsyer/petclinic                    # Filter/Match
    newName: 10.38.48.51:5000/demo/petclinic # Replace
    newTag: 4.0.1-SNAPSHOT                   # Appends to name. 
