apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pet-clinic
resources:
  - namespace.yaml
  - db.yaml
  - petclinic.yaml
  - ingress.yaml

# Update images
images:
  - name: dsyer/petclinic                    # Filter/Match
    newName: 10.38.48.51:5000/demo/petclinic # Replace
    newTag: 4.0.0-SNAPSHOT                   # Appends to name. 

# Update ingress to match
patches:
  - target:
      kind: Ingress
      name: spring-cloud-petclinic-service
    patch: |
      # 1. Update the routing rule to match your raw IP address
      - op: replace
        path: /spec/rules/0/host
        value: "petclinic.local" # <-- Replace this with your FQDN

      # 2. Completely strip out the TLS block
      # (Browsers and Cert-Manager will fail/complain if you try to force TLS onto a raw IP)
      # - op: remove
      #   path: /spec/tls