---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    role: frontend
    tier: web

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    role: frontend
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
      tier: web
  template:
    metadata:
      labels:
        role: frontend
        tier: web
    spec:
      containers:
        - name: workload
          image: dsyer/petclinic
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: postgres

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: demo-db-app
                  key: jdbc-uri

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: demo-db-app
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db-app
                  key: password

            - name: SPRING_APPLICATION_JSON
              value: |
                {
                  "management.endpoint.health.probes.add-additional-paths": true
                }
          ports:
            - name: http
              containerPort: 8080
          startupProbe:
            httpGet:
              path: /livez
              port: http
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /livez
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            periodSeconds: 5
